const rootPathKey = 'rootPath'
//发布localstorage key
const PUBLISH_PROJECT_KEY = 'publishProject'

enum callFnName {
  getState = "getState",
  GetSysConfig = "GetSysConfig",
  SaveSysConfig = "SaveSysConfig",
  ShowDirSelect = "ShowDirSelect",
  GetPrinterList = "GetPrinterList",
  GetDevcieConfigs = "GetDevcieConfigs",
  SaveDevcieConfig = "SaveDevcieConfig",
  DeleteDevcieConfig = "DeleteDevcieConfig",
  getSupportDevices = "getSupportDevices",
  GetCategoryNodes = "GetCategoryNodes",
  saveCategoryNode = "saveCategoryNode",
  deleteCategoryNode = "deleteCategoryNode",
  GetCategoryDatas = "GetCategoryDatas",
  saveCategoryData = "saveCategoryData",
  deleteCategoryData = "deleteCategoryData",
  GetDataConfigs = "GetDataConfigs",
  saveDataConfig = "saveDataConfig",
  deleteDataConfig = "deleteDataConfig",
  initDataConfig = "initDataConfig",
  GetFormulaConfigs = "GetFormulaConfigs",
  getFormulaDatas = "getFormulaDatas",
  GetProductStatistics = "GetProductStatistics",
  GetProductLogs = "GetProductLogs",
  deleteProductHistory = "deleteProductHistory",
  GetSerialNo = "GetSerialNo",
  GetSerialNos = "GetSerialNos",
  SaveSerialNo = "SaveSerialNo",
  DeleteSerialNo = "DeleteSerialNo",
  getNewSerialNo = "getNewSerialNo",
  getFullCollectPoints = "getFullCollectPoints",
  GetCpkData = "GetCpkData",
  startSpcSystem = 'startSpcSystem',
  CloseApp = 'CloseApp',
  showDevTools = 'showDevTools',
  closeSpcSystem = `closeSpcSystem`,
  StartCollect = `StartCollect`,
  openDevTool = `openDevTool`,
  InitService = `InitService`,
  InitDevice = `InitDevice`,
  GetDataAddresses = `GetDataAddresses`,
  GetDevcieDrivers = `GetDevcieDrivers`,
  SaveDataAddress = `SaveDataAddress`,
  DeleteDataAddress = `DeleteDataAddress`,
  GetDataGroups = `GetDataGroups`,
  SaveDataGroup = `SaveDataGroup`,
  EnableDataGroup = `EnableDataGroup`,
  DeleteDataGroup = 'DeleteDataGroup',
  GetDataAddressesWithIds = `GetDataAddressesWithIds`,
  SaveDataGroupOnlyName = `SaveDataGroupOnlyName`,
  EnableFormulaConfig = `EnableFormulaConfig`,
  DeleteFormulaConfig = `DeleteFormulaConfig`,
  GetFormulaFields = `GetFormulaFields`,
  GetFormulaParams = `GetFormulaParams`,
  SaveFormulaParams = `SaveFormulaParams`,
  DeleteProductHistorys = `DeleteProductHistorys`,
  DeleteProductHistory = `DeleteProductHistory`,
  ShaftCollect = `ShaftCollect`,
  GetRealtimeData = `GetRealtimeData`,
  GetChartDataAddress = `GetChartDataAddress`,
  GetChartData = `GetChartData`,
  GetShowDataAddress = `GetShowDataAddress`,
  GetDistributionData = `GetDistributionData`,
  GetGroupConfigs = `GetGroupConfigs`,
  SaveGroupConfig = `SaveGroupConfig`,
  EnableGroupConfig = `EnableGroupConfig`,
  DeleteGroupConfig = `DeleteGroupConfig`,
  GetDeviceGroups = `GetDeviceGroups`,
  SaveDeviceGroup = `SaveDeviceGroup`,
  DeleteDeviceGroup = `DeleteDeviceGroup`,
  GetChartDeviceGroups = `GetChartDeviceGroups`,
  GetShowDeviceGroups = `GetShowDeviceGroups`,
  GetDataClass = `GetDataClass`,
  GetDeviceClass = `GetDeviceClass`,
  GetChartDataGroups = `GetChartDataGroups`,
  GetShowDataGroups = `GetShowDataGroups`,
  RestartApp = `RestartApp`,
  ShutdownPc = `ShutdownPc`,
  OpenFile = `OpenFile`,
  SaveExportImage = `SaveExportImage`,
  SaveFormulaConfig = `SaveFormulaConfig`, activeFormulaConfig = 'activeFormulaConfig', GetProductHistorys = 'GetProductHistorys', StopCollect = "StopCollect",
  CalcWallThickness = `CalcWallThickness`,
  CalcConcentricity = `CalcConcentricity`,
  getSpanCollectPoints = `getSpanCollectPoints`, getNormalDistribution = 'getNormalDistribution', ClearCollect = 'ClearCollect',
  getFFT = `getFFT`, showKeyBoard = `showKeyBoard`, initKeyboardConfig = `initKeyboardConfig`, checkRegister = `checkRegister`, getMachineCode = `getMachineCode`, getRegisterState = `getRegisterState`, getRegisterCode = `getRegisterCode`, KeyPress = `KeyPress`, KeyDown = `KeyDown`, KeyUp = `KeyUp`, getLastPoint = `getLastPoint`,
  GetWallThickness = "GetWallThickness",
  /** 保存图片等资源到宿主 Resources/pic（参数 fileName, base64/dataURL），返回 https://pic.nt.local/ 下的 URL */
  SaveResourceFile = "SaveResourceFile",
  /** 列出 Resources/pic 里的资源文件（无参数），返回 [{ FileName, RelativePath, Url, Size, LastModifiedUtc }] */
  ListResourceFiles = "ListResourceFiles",
  /** 删除 Resources/pic 里的一个资源文件（参数 fileName，纯文件名），返回 { FileName, RelativePath, Deleted } */
  DeleteResourceFile = "DeleteResourceFile",
  /** 导出数据组态包（参数 layoutJson, targetPath；targetPath 为空时宿主弹「另存为」），返回 { Cancelled, Path, FileName, Size, Widgets, Resources, Missing } */
  ExportScadaPackage = "ExportScadaPackage",
  /** 选择并清点组态包（参数 packagePath；为空时宿主弹打开文件对话框），返回 { Cancelled, Path, FileName, Widgets, Canvas, Resources, ToCopy, Reusable, Missing, Files } */
  PreviewScadaPackage = "PreviewScadaPackage",
  /** 导入组态包（参数 packagePath）：宿主把缺的资源解压到 Resources/pic，返回 { Layout, Widgets, Copied, Reused, Missing, Failed } */
  ImportScadaPackage = "ImportScadaPackage"
}

export {
  rootPathKey, PUBLISH_PROJECT_KEY, callFnName
}
